global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-2
        access_key: yourkey
        secret_key: yourkey
        port: 9100
      
# scrape_configs:
#   - job_name: 'node'
#     ec2_sd_configs:
#       - region: ca-central-1 
#         profile: default
#         port: 9100
