global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: ca-central-1
        port: 9100

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']

rule_files:
  - "alertmanager-rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093